apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: wisecowtest
spec:
  # 3 Pods should exist at all times.
  replicas: 2
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: wisecow
    spec:
      containers:
      - name: wisecow
        # Run this image
        image: ravikumarsl93/wisecowtest:demo
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: LoadBalancer
